name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: LeetCode Sync
        uses: joshcai/leetcode-sync@v1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          destination-folder: my-leetcode-solutions
